[package]
name = "be"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = "2.2.9"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.16.0", features = ["v4", "serde"] }

